sudo: required

services:
  - docker

language: go
go: 1.9
env:
  - DEP_VERSION="0.3.2"

before_install:
  # Setup some env variables
  - GO_FILES=$(find . -iname '*.go' )  # All the .go files
  - PKGS=$(go list ./... )             # All the import paths

  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  # To install latest version, use `go get -u github.com/golang/dep/cmd/dep`

  # Install linters
  - go get -u github.com/golang/lint/golint              # Linter
  - go get -u honnef.co/go/tools/cmd/megacheck           # Badass static analyzer/linter
  - go get -u github.com/kisielk/errcheck                # errcheck checks that you checked errors.

install:
  - dep ensure

script:
  - test -z $(gofmt -s -l $GO_FILES)  # Fail if a .go file hasn't been formatted with gofmt
  - go vet -v $PKGS                      # go vet is the official Go static analyzer
  - megacheck $PKGS                   # "go vet on steroids" + linter
  - errcheck $PKGS                    # Check for unchecked errors
  - golint -set_exit_status $PKGS     # One last linter

  # Run all the tests
  - go test -v $PKGS
