language: go

go: 1.9

env:
  - GO_ENV=test DB_URL="mongodb://127.0.0.1:27017"

services:
  - mongodb
  - docker

go_import_path: github.com/aiotrc/pm

before_install:
  - PKGS=$(go list ./... ) # All the import paths
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh # go dep
  - go get -u github.com/golang/lint/golint   # linter
  - go get -u github.com/kisielk/errcheck     # errcheck checks that you checked errors.

install:
  - go get github.com/gobuffalo/buffalo/buffalo
  - dep ensure
  - docker pull aiotrc/gorunner
  - docker pull redis:alpine
  - docker network create isrc

before_script:
  - buffalo task mongo

script:
  - go vet -v $PKGS                   # go vet is the official Go static analyzer
  - errcheck -verbose $PKGS           # Check for unchecked errors
  - golint -set_exit_status $PKGS     # One last linter
  - buffalo test
