swagger: "2.0"
info:
  title: Project Manager
  version: v2

paths:
  /about:
    get:
      operationId: about
      description: Memory of 18.20
      produeces:
        - application/json
      responses:
        200:
          description: "18.20 is leaving us"
          schema:
            type: string
  /api/projects:
    get:
      operationId: listProjects
      description: Gets all projects
    post:
      operationId: createProject
      description: Creates new project
